### ISSUE TITLE
Solver timed out 

### ISSUE THREAD

**Issue by tuchandra** [grantm/sudoku-web-app#11]
This puzzle causes the solver to time out while checking for a unique solution—

https://sudokuexchange.com/play/?s=000007004000006003860200000509082000640000080000000700000000042010030000703000009

I do believe it has a unique solution (I just checked on [SudokuSolver.net](https://sudokusolver.net/#)). I also can't seem to repro this every time I refresh / reopen this page, only some of the time. This still lets me play the puzzle, so not a huge deal, but wanted to report it.

**Comment by grantm** [comment]
The solver code that checks for a unique solution is just a brute force algorithm checking every possible digit in every position. Because it runs before the puzzle is rendered on screen, the user can be left staring at a blank screen for quite some time (minutes in the case of some pathological arrangements). For that reason, I've set a 3 second timeout on the solver, after which it will, give up issue a warning, and then let the user carry on.
The number of possible solutions that can be checked in 3 seconds will depend on the speed of your computer (/device) and what else it's doing. For example my laptop finds a unique solution for that puzzle in significantly less than a second.
I could look at changing the warning dialog to include a "Keep checking" button.

**Comment by tuchandra** [comment]
That's fine! It's of course up to you to decide what to do (if anything). I appreciate this project a lot and only wanted to report in case you weren't aware / wanted to do something about it. Thank you for your hard work!
