### ISSUE TITLE
Freeze on page load.

### ISSUE THREAD

**Issue by metalim** [grantm/sudoku-web-app#4]
Some starting combinations halt the page.
[This](https://sudokuexchange.com/play/?s=001000000200000000003000000400000005005000600600000040007103000800000000009020000).
I was trying out knight moves.

**Comment by grantm** [comment]
Ouch that's not good.  This is almost certainly happening in the code path that attempts to confirm the puzzle has a unique solution.  In your case it should eventually issue a warning since this app doesn't know about the knight's move constraint (yet?). However there's no way it should be taking that long to determine there's more than one solution.

**Comment by grantm** [comment]
Upon further investigation, this is rather a pathological case for my brute force 'solver' and it really does need to backtrack a bazillion times, to find even one possible solution (after which it would immediately find a second). Interestingly if the arrangement of starting digits are rotated 90° clockwise, the solver is able to almost instantaneously determine there is more than one solution.
In your case, since you're not actually interested in the solver's findings it's probably better for the solver to "fail fast". So I'll modify it to behave like the [SudokuWiki solver](https://www.sudokuwiki.org/sudoku.htm?bd=001000000200000000003000000400000005005000600600000040007103000800000000009020000) and not even try when there are fewer than 17 given digits.
I will still have it issue a warning: 'This arrangement may not have a unique solution'
