### ISSUE TITLE
Time running backwards on solved puzzles

### ISSUE THREAD

**Issue by jtmcdole** [grantm/sudoku-web-app#46]
Thrice now I've switched tabs on solved puzzles only to switch back and see the solve timer has gone in reverse by the same amount of time I've been away.

1. Play a game
2. Win
3. Note timer
3. Switch away for a couple of seconds and come back
4. See timer is shorter than before.

**Comment by grantm** [comment]
Thanks for taking the time to report this.

It is a new feature of the most recent release that the timer is meant to pause when you switch away to another tab and then resume when you return.  I had noticed that due to rounding errors, it's common for the timer to go backwards 1 second when it resumes.

Are you seeing the timer go more than one second backwards?  If so can you please tell me a bit more about your setup - Operating system (Windows/MacOS/iOS/Android/Linux etc.) and browser (Firefox/Chrome/Edge/Safari etc.).

**Comment by grantm** [comment]
Ah, I see the problem - I missed the bit in your report where you said *solved* puzzles - Doh!

**Comment by jtmcdole** [comment]
Chrome browser on Windows 10. And it goes back way more than a second :)

**Comment by grantm** [comment]
The web app at https://sudokuexchange.com/play/ has been updated with the fix for this issue.
Thanks again for reporting it.
